HW1
ark-1/au-java pull request #1
Opened 2019-01-24 11:27 UTC by ark-1

2019-01-28 17:00 UTC, jzuken requested changes

2019-01-28 17:00 UTC, jzuken commented on hw1/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
лучше всё же на пятый перейти

2019-01-28 17:00 UTC, jzuken commented on hw1/src/main/java/me/arkadybazhanov/au/java/hw1/Hashtable.java
> +            if (entry.key.equals(key)) return true;
лучше писать на разных строках

2019-01-28 17:00 UTC, jzuken commented on hw1/src/main/java/me/arkadybazhanov/au/java/hw1/Hashtable.java
> +    public @Nullable String put(@NotNull String key, @NotNull String value) {
а если аргумент null, можно бросить исключение

2019-01-28 17:00 UTC, jzuken commented on hw1/src/main/java/me/arkadybazhanov/au/java/hw1/Hashtable.java
> +        public @NotNull String key;
их вполне можно было бы тоже сделать private

2019-01-28 17:10 UTC, ark-1 commented on hw1/src/main/java/me/arkadybazhanov/au/java/hw1/Hashtable.java
> +    public @Nullable String put(@NotNull String key, @NotNull String value) {
вроде обсудили на паре, что NotNull-контрактов достаточно. если писать null-check каждый раз, когда принимаешь @NotNull аргумент, идея говорит "ты что, глупый? оно не может быть null"

2019-01-29 10:55 UTC, jzuken commented on hw1/src/main/java/me/arkadybazhanov/au/java/hw1/Hashtable.java
> +    public @Nullable String put(@NotNull String key, @NotNull String value) {
а, да, точно

2019-02-11 15:38 UTC, jzuken commented
мне бы доступ на запись сюда ещё

2019-02-12 09:31 UTC, jzuken commented
конфликт бы поправить

2019-02-12 13:53 UTC, merged